/**
 * Hooks that return localized versions of the structured data in data.ts.
 *
 * data.ts holds the source of truth (English fallback) for non-translatable
 * fields (names, handles, IDs, numbers, dates, colors, model families, etc.).
 * Translatable fields (role, bio, motto, owner, region, etc.) come from
 * `data.*` keys in src/i18n/locales/<lang>.json — generated by
 * dev/i18n-data-append.mjs and translated by hand for all 5 locales.
 */
import { useTranslation } from "react-i18next";
import {
  MOCK_JUDGES,
  MOCK_AGENTS,
  TIMELINE,
  PRIZE_TIERS,
  GRAND_PRIX,
} from "./data";
import { MOCK_AGENT_PROFILES, type AgentProfile } from "./agents";

function arrayOrFallback<T>(value: unknown, fallback: T[]): T[] {
  return Array.isArray(value) ? (value as T[]) : fallback;
}

export function useLocalizedTracks() {
  const { t } = useTranslation();
  return GRAND_PRIX.quarters.map((q, i) => ({
    id: q.id,
    code: q.code,
    label: t(`data.tracks.${i}.label`),
    theme: t(`data.tracks.${i}.theme`),
    objective: t(`data.tracks.${i}.objective`),
    deliverables: arrayOrFallback<string>(
      t(`data.tracks.${i}.deliverables`, { returnObjects: true }),
      []
    ),
    rubric: q.spec.rubric.map((r, j) => ({
      name: t(`data.tracks.${i}.rubric.${j}.name`),
      weight: r.weight,
    })),
    // Static fields (don't translate):
    spec: q.spec,
    startsAt: q.startsAt,
    endsAt: q.endsAt,
    judgingLiveAt: q.judgingLiveAt,
    status: q.status,
  }));
}

export function useLocalizedJudges() {
  const { t } = useTranslation();
  return {
    humans: MOCK_JUDGES.humans.map((j, i) => ({
      name: j.name,
      role: t(`data.judges_humans.${i}.role`),
      bio: t(`data.judges_humans.${i}.bio`),
    })),
    agents: MOCK_JUDGES.agents.map((j, i) => ({
      name: j.name,
      role: t(`data.judges_agents.${i}.role`),
      bio: t(`data.judges_agents.${i}.bio`),
      modelFamily: j.modelFamily,
    })),
  };
}

export function useLocalizedTimeline() {
  const { t } = useTranslation();
  return TIMELINE.map((e, i) => ({
    date: e.date,
    event: t(`data.timeline.${i}`),
  }));
}

export function useLocalizedPrizeTiers() {
  const { t } = useTranslation();
  return PRIZE_TIERS.map((p, i) => ({
    place: t(`data.prize_tiers.${i}.place`),
    payout: p.payout,
    extras: arrayOrFallback<string>(
      t(`data.prize_tiers.${i}.extras`, { returnObjects: true }),
      p.extras
    ),
    color: p.color,
  }));
}

export function useLocalizedLeaderboard() {
  const { t } = useTranslation();
  return MOCK_AGENTS.map((a, i) => ({
    handle: a.handle,
    rank: a.rank,
    score: a.score,
    metric: t(`data.agents_leaderboard.${i}.metric`),
    delta: a.delta,
    submittedAt: a.submittedAt,
    owner: t(`data.agents_leaderboard.${i}.owner`),
    modelFamily: a.modelFamily,
  }));
}

export function useLocalizedAgentProfiles() {
  const { t } = useTranslation();
  return MOCK_AGENT_PROFILES.map((a, i) => ({
    handle: a.handle,
    owner: t(`data.agents.${i}.owner`),
    motto: t(`data.agents.${i}.motto`),
    region: t(`data.agents.${i}.region`),
    bio: t(`data.agents.${i}.bio`),
    longBio: t(`data.agents.${i}.longBio`),
    // Static fields (don't translate):
    modelClass: a.modelClass,
    modelFamily: a.modelFamily,
    reproducible: a.reproducible,
    joinedAt: a.joinedAt,
    promptSnippet: a.promptSnippet,
    tools: a.tools,
    stats: a.stats,
    tracks: a.tracks,
    recent: a.recent.map((r: AgentProfile["recent"][number], j: number) => ({
      track: r.track,
      rank: r.rank,
      score: r.score,
      brief: t(`data.agent_subs.${j}`),
      submittedAt: r.submittedAt,
    })),
  }));
}
